force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resources__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Rate_Hour__c.field-meta.xml
<CustomField>
    <fullName>Rate_Hour__c</fullName>
    <label>Rate Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ResourceWrapper.cls
public with sharing class ResourceWrapper {
  public Id id;
  public String firstName;
  public String lastName;
  public Decimal rateHour;
  public Id roleId;

  public ResourceWrapper(Project_Resources__c projectResource) {
    this.id = projectResource.Resource__c;
    this.firstName = projectResource.Resource__r.FirstName;
    this.lastName = projectResource.Resource__r.LastName;
    this.rateHour = projectResource.Resource__r.Rate_Hour__c;
    this.roleId = projectResource.Resource__r.UserRoleId;
  }
}