force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resources__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <formula>Resource__r.UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Rate_Hour__c.field-meta.xml
<CustomField>
    <fullName>Rate_Hour__c</fullName>
    <label>Rate Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ResourceServiceTest.cls
@isTest
public class ResourceServiceTest {
  // Project              S-------E
  // User       s---------e
  // User                         s---------e
  // User3    s--------e      s---------e
  // User           s---------e

  // User2    s--------e             s---------e
  // User1      [---]   [---]  [---]  [----]

  @isTest
  static void shoudlReturnErikaAndMaxi() {
    User erika = new User(
      FirsName = 'Erika',
      LastName = 'A',
      Rol__c = 'Arquitect',
      Rate_Hour__c = 10
    );
    User max = new User(
      FirstName = 'Maxi',
      LastName = 'B',
      Rol__c = 'Developer',
      Rate_Hour__c = 9
    );

    Project_Resources__c erika = 
  }
}