force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resources__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Rate_Hour__c.field-meta.xml
<CustomField>
    <fullName>Rate_Hour__c</fullName>
    <label>Rate Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ResourceService.cls
public with sharing class ResourceService {
  public static List<ResourceWrapper> queryAvailableResources(
    Date projectStartDate,
    Date projectEndDate
  ) {
    Map<Id, ResourceWrapper> availableResources = new Map<Id, ResourceWrapper>();

    List<Project_Resources__c> projectResources = [
      SELECT
        Resource__c,
        Resource__r.FirstName,
        Resource__r.LastName,
        Resource__r.Rate_Hour__c,
        Resource__r.UserRoleId
      FROM Project_Resources__c
      WHERE End_Date__c <= :projectStartDate OR Start_Date__c >= :projectEndDate
    ];

    for (Project_Resources__c resource : projectResources) {
      if (!availableResources.containsKey(resource.Resource__c)) {
        availableResources.put(
          resource.Resource__c,
          new ResourceWrapper(resource)
        );
      }
    }

    return availableResources.values();
  }
}