force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>ProjectLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Sold Roles</relationshipLabel>
    <relationshipName>ProjectLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectWrapper.cls
public with sharing class ProjectWrapper {
  public Id projectId;
  public String projectStart;
  public String projectEnd;
  public List<PositionWrapper> projectLineItems = new List<PositionWrapper>();

  public ProjectWrapper(Project__c project) {
    this.projectId = project.Id;
    this.projectStart = project.Start_Date__c.format();
    this.projectEnd = project.End_Date__c.format();
    this.configurePositions(project.ProjectLineItems__r);
  }

  private void configurePositions(List<ProjectLineItem__c> positions) {
    for (ProjectLineItem__c position : positions) {
      this.projectLineItems.add(new PositionWrapper(position));
    }
  }
}