force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/AssignedTotalHours__c.field-meta.xml
<CustomField>
    <fullName>AssignedTotalHours__c</fullName>
    <label>AssignedTotalHours</label>
    <summarizedField>ProjectLineItem__c.AssignedHousxRol__c</summarizedField>
    <summaryForeignKey>ProjectLineItem__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Cost__c</fullName>
    <label>Estimated Cost</label>
    <summarizedField>ProjectLineItem__c.Estimated_Cost__c</summarizedField>
    <summaryForeignKey>ProjectLineItem__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Sold_Hours__c.field-meta.xml
<CustomField>
    <fullName>Sold_Hours__c</fullName>
    <label>Sold Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Projects (Squad Lead)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Financial loss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeStatus.cls
public with sharing class ChangeStatus implements Schedulable{
    public void execute(SchedulableContext SC) {

        ChangeStatusProject();
 
     }


    public static void ChangeStatusProject(){
        List<Project__c> projectList = [SELECT Id, Status__c, Sold_Hours__c, Squad_Lead__c, Revenue__c, Estimated_Cost__c,AssignedTotalHours__c FROM Project__c WHERE Status__c = 'Pre-kickoff' AND Start_Date__c = TODAY];
        for(Project__c project : projectList){


            if(project.AssignedTotalHours__c >= project.Sold_Hours__c && project.Squad_Lead__c != null && project.Revenue__c > project.Estimated_Cost__c)
            {
                project.Status__c = 'In progress';
            }
           
        }
        update projectList;
    }







}