force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Financial loss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resources__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resources__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Tasks</label>
    <nameField>
        <label>Project_Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Estimated_Hour__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Hour__c</fullName>
    <label>Estimated Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project_Resource__c.field-meta.xml
<CustomField>
    <fullName>Project_Resource__c</fullName>
    <label>Project Resource</label>
    <referenceTo>Project_Resources__c</referenceTo>
    <relationshipLabel>Project_Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectTaskController.cls
public with sharing class ProjectTaskController {
    @AuraEnabled(cacheable=true)
    public static List<Project_Task__c> getProjectTasks() {
        return [SELECT Id, Name, Status__c, Estimated_Hour__c, Registered_Hours__c, Project__c, Project__r.Name,
        Project__r.Start_Date__c, Start_Date__c
                FROM Project_Task__c
                WHERE Project_Resource__r.Resource__c =: UserInfo.getUserId() AND Project__c != null AND Status__c != 'Completed' ORDER BY Project__r.Start_Date__c ASC, Status__c DESC, Start_Date__c ASC];
    }


    public class ProjectTaskWrapper{
        @auraEnabled
        public List <Project_Task__c> tasks;

        public ProjectTaskWrapper(List <Project_Task__c> tasks)
        {
            this.tasks = tasks;
        }
    }




    //obtener los project_task__c filtradas por usuario logueado



    @AuraEnabled(cacheable=true)
    public static ProjectTaskWrapper getProjectTasksByUser(Id user) {
        List<Project_Task__c> projectTasks = [SELECT Name, Status__c, Estimated_Hour__c, Registered_Hours__c, Project__c, Project__r.Name,Project_Resource__r.Resource__c
                FROM Project_Task__c
                WHERE Project__c != null AND Project_Resource__r.Resource__c= :user AND Status__c != 'Completed' ORDER BY Status__c DESC];
        return new ProjectTaskWrapper(projectTasks);
       
    }


    //cambiamos el estado de la tarea a completed
    @AuraEnabled
    public static Boolean changeStatus (Id taskId,string state)
    {
        Boolean satatusToUp = false;
        
            Project_Task__c task = [SELECT Id, Status__c FROM Project_Task__c WHERE Id = :taskId];
            task.Status__c = state;
            
            if(task != null)
            {
                update task;
                satatusToUp = true;
            }
            return satatusToUp;
       

    }



    //registramos las horas

    @AuraEnabled
    public static Boolean registerHours (Id taskId,Integer hours)
    {
        Boolean satatusToUp = false;
        
            Project_Task__c task = [SELECT Id, Registered_Hours__c FROM Project_Task__c WHERE Id = :taskId];
            task.Registered_Hours__c +=  hours;
            
            if(task != null)
            {
                update task;
                satatusToUp = true;
            }
            return satatusToUp;
       

    }










}