force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Cost__c</fullName>
    <label>Estimated Cost</label>
    <summarizedField>ProjectLineItem__c.Estimated_Cost__c</summarizedField>
    <summaryForeignKey>ProjectLineItem__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Projects (Squad Lead)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Financial loss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resources__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resources__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Tasks</label>
    <nameField>
        <label>Project_Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/validateProjectHandler.cls
public with sharing class validateProjectHandler {
    public static void validateProjectCompletion(List<Project__c> projectList) {
        // Recopilamos todos los ID de Proyectos que están siendo actualizados
        Set<Id> projectIds = new Set<Id>();
        for (Project__c project : projectList) {
            projectIds.add(project.Id);
        }
    
        // Buscamos todas las ProjectTask__c relacionadas con los proyectos en actualización
        List<Project_Task__c> projectTasks = [        SELECT Id, Status__c, Project__c        FROM Project_Task__c        WHERE Project__c IN :projectIds    ];
    
      
        


        // Iteramos por cada Project__c actualizado y verificamos si está siendo marcado como "Completed"
        for (Project__c project : projectList) {
            if (project.Status__c == 'Completed') {
                // Iteramos por cada ProjectTask__c relacionada y verificamos si alguna no ha sido completada
                for (Project_Task__c projectTask : projectTasks) {
                    if (projectTask.Project__c == project.Id && projectTask.Status__c != 'Completed') {
                        // Si hay una ProjectTask__c relacionada con estado diferente de "Completed", lanzamos una excepción
                        project.addError('No puedes marcar este proyecto como "Completed" porque aún hay tareas pendientes.');
                        break;
                    }
                }

            }

          
        }

    }

    public static void assignSquadLead(List<Project__c> projectList, Map<Id, Project__c> oldMap) {
        if (oldMap.isEmpty()) { // Se crea un nuevo registro
            for (Project__c project : projectList) {
                if (project.Squad_Lead__c != null) {
                    project.addError('No se puede asignar un Squad Lead al crear un nuevo proyecto');
                }
            }
        } else { // Se actualiza un registro existente
            Set<Id> projectIds = new Set<Id>();
            for (Project__c project : projectList) {
                projectIds.add(project.Id);
            } 
    
            Set<Id> projectResourceIds = new Set<Id>();
            List<Project_Resources__c> projects = [SELECT Id, Resource__c, Project__c FROM Project_Resources__c WHERE Project__c IN :projectIds];
            for(Project_Resources__c project : projects){
                projectResourceIds.add(project.Resource__c);
            }
    
            for (Project__c project : projectList) {
              /*  if (project.Status__c != 'Pre-Kickoff') {
                    project.addError('No se puede asignar al Squad Lead ya que el proyecto no está en el estado "Pre-Kickoff".');
                } */
    
                 if(oldMap.get(project.Id).Status__c == 'Pre-Kickoff' && (project.Status__c == 'In progress' || project.Status__c == 'Completed'))
                {
                    if (project.Squad_Lead__c == null) {
                          project.addError('El campo Squad Lead no puede ser nulo al actualizar un proyecto');
                        //System.debug('El campo Squad Lead no puede ser nulo al actualizar un proyecto');
                      } else if (!projectResourceIds.contains(project.Squad_Lead__c)  ) {
                          project.addError('No se puede asignar al Squad Lead ya que no corresponde al proyecto');
                      }
                }
                 if ( project.Squad_Lead__c != null && !projectResourceIds.contains(project.Squad_Lead__c)  ) {
                    project.addError('No se puede asignar al Squad Lead ya que no corresponde al proyecto');
                }
                if(oldMap.get(project.Id).Status__c == 'Financial loss' && project.Status__c == 'In progress' )
                {
                    if(project.Estimated_Cost__c > project.Revenue__c)
                    {
                        project.addError('El costo estimado no puede ser mayor a los ingresos');
                    }	
                   
                }
                if(project.Estimated_Cost__c > project.Revenue__c)
                {
                    project.Status__c='Financial loss';
                }
            }
        }
    }
    
    /* public static void statusLoss(List<Project__c> projectList) 
    {
        for (Project__c project : projectList) {
            if(project.Estimated_Cost__c > project.Revenue__c)
            {
                project.Status__c='Financial loss';
            }
        }
    } */

 }