force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>ProjectLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/AssignedHousxRol__c.field-meta.xml
<CustomField>
    <fullName>AssignedHousxRol__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AssignedHousxRol</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/SodlHoursToCover__c.field-meta.xml
<CustomField>
    <fullName>SodlHoursToCover__c</fullName>
    <formula>Project__r.Sold_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SodlHoursToCover</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PositionWrapper.cls
public with sharing class PositionWrapper {
  public String positionId;
  public String role;
  public Decimal soldHoursToCover;
  public Decimal assignedHours;
  public List<ResourceWrapper> availableResource = new List<ResourceWrapper>();

  public PositionWrapper(ProjectLineItem__c position) {
    this.positionId = position.Id;
    this.role = position.Rol__c;
    this.soldHoursToCover = position.SodlHoursToCover__c;
    assignedHours = position.AssignedHousxRol__c;
  }
}